version: "3"

services:
  cassandra-1:
    container_name: cassandra-1
    networks:
      - dbnet
    hostname: cassandra-1
    image: alex202/cassandra:3.11
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-1
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=200M

  cassandra-2:
    container_name: cassandra-2
    networks:
      - dbnet
    hostname: cassandra-2
    image: alex202/cassandra:3.11
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=200M

  cassandra-3:
    container_name: cassandra-3
    networks:
      - dbnet
    hostname: cassandra-3
    image: alex202/cassandra:3.11
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=200M 

networks:
  vnet:
    external:
      name: dbnet
